# Generated by Django 5.1.3 on 2024-12-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_duration_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tiredness_factor',
            field=models.CharField(choices=[('relaxing', 'Relaxing'), ('neutral', 'Neutral'), ('draining', 'Draining')], max_length=50),
        ),
    ]
